# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuadroClinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=50)),
                ('nombre_formal', models.CharField(max_length=20)),
                ('nombre_comun', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nombre_cientifico', models.CharField(max_length=20)),
                ('epidemiologia', models.CharField(max_length=30)),
                ('duracion', models.CharField(max_length=10)),
                ('distribucion', models.CharField(max_length=20)),
            ],
        ),
    ]
