# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=20)),
                ('nombre_cientifico', models.CharField(max_length=30)),
                ('principios_activos', models.TextField(max_length=100)),
                ('efectos_secundarios', models.TextField(max_length=100)),
                ('indicaciones', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.TextField()),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
    ]
