# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('director', models.CharField(blank=True, max_length=20)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centrodesalud.Clinica')),
            ],
        ),
    ]
